// SPDX-License-Identifier: MIT

package server

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/kwad77/pincher/internal/db"
)

// Schema diet (#2003) — Phase 1 measurement + permanent regression gate.
//
// The messy-corpus loopbench run (PR #2002) measured ~46.5k tokens of
// MCP tool schemas cache-created at session start for the pincher arm
// vs ~27k for native arms — re-read every turn, and the reason a
// 10/10-accuracy, 22-vs-36-turn pincher run still lost on tokens.
// These tests make that weight a first-class, committed number:
//
//   - TestSchemaWeight_Report renders every MCP-visible tool exactly as
//     a tools/list client receives it (name + title + description +
//     inputSchema + annotations), weighs it with db.ApproxTokens, and
//     pins the per-tool table + the full/core × rich/lean totals to
//     testdata/schema-weight.md. Any schema growth shows up as a
//     reviewable diff. Regenerate with:
//     go test ./internal/server/ -run TestSchemaWeight_Report -update-schema-weight
//
//   - TestSchemaWeight_CoreLean_UnderBudget is the hard gate: the
//     core-toolset + lean-style surface must stay under
//     coreLeanTokenBudget approximate tokens.

var updateSchemaWeight = flag.Bool("update-schema-weight", false,
	"rewrite testdata/schema-weight.md instead of asserting against it")

// coreLeanTokenBudget is the hard ceiling (approximate tokens,
// db.ApproxTokens chars/4 heuristic) for the PINCHER_TOOLSET=core +
// PINCHER_SCHEMA_STYLE=lean tools/list surface. Set from the Phase-1
// measurement with headroom for organic arg additions; raising it is a
// deliberate, reviewed decision.
const coreLeanTokenBudget = 4000

// clientToolEntry is the tools/list wire shape a client pays for, in
// the SDK's field order. Annotations and Title are included because
// the client receives them too — the weight must be honest.
type clientToolEntry struct {
	Name        string          `json:"name"`
	Title       string          `json:"title,omitempty"`
	Description string          `json:"description"`
	InputSchema json.RawMessage `json:"inputSchema"`
	Annotations any             `json:"annotations,omitempty"`
}

// schemaWeights renders every MCP-visible tool on srv as a client
// receives it and returns per-tool approximate token weights plus the
// total.
func schemaWeights(t *testing.T, srv *Server) (map[string]int, int) {
	t.Helper()
	perTool := make(map[string]int, len(srv.mcpVisible))
	total := 0
	for name := range srv.mcpVisible {
		tool := srv.tools[name]
		if tool == nil {
			t.Fatalf("mcpVisible tool %q missing from s.tools", name)
		}
		rawSchema, err := json.Marshal(tool.InputSchema)
		if err != nil {
			t.Fatalf("marshal %q InputSchema: %v", name, err)
		}
		entry := clientToolEntry{
			Name:        tool.Name,
			Title:       tool.Title,
			Description: tool.Description,
			InputSchema: rawSchema,
		}
		if tool.Annotations != nil {
			entry.Annotations = tool.Annotations
		}
		b, err := json.Marshal(entry)
		if err != nil {
			t.Fatalf("marshal %q entry: %v", name, err)
		}
		w := db.ApproxTokens(string(b))
		perTool[name] = w
		total += w
	}
	return perTool, total
}

// newSchemaWeightServer builds a server under the given toolset/style
// env. Not parallel-safe (t.Setenv); callers run sequentially.
func newSchemaWeightServer(t *testing.T, toolset, style string) *Server {
	t.Helper()
	t.Setenv("PINCHER_TOOLSET", toolset)
	t.Setenv("PINCHER_SCHEMA_STYLE", style)
	srv, _, _ := newTestServer(t)
	return srv
}

func TestSchemaWeight_Report(t *testing.T) {
	combos := []struct{ toolset, style string }{
		{"full", "rich"},
		{"full", "lean"},
		{"core", "rich"},
		{"core", "lean"},
	}
	totals := make(map[string]int, len(combos))
	var fullRich map[string]int
	for _, c := range combos {
		srv := newSchemaWeightServer(t, c.toolset, c.style)
		perTool, total := schemaWeights(t, srv)
		totals[c.toolset+"/"+c.style] = total
		if c.toolset == "full" && c.style == "rich" {
			fullRich = perTool
		}
	}

	// Per-tool table, heaviest first (full/rich — the shipped default).
	names := make([]string, 0, len(fullRich))
	for name := range fullRich {
		names = append(names, name)
	}
	sort.Slice(names, func(i, j int) bool {
		if fullRich[names[i]] != fullRich[names[j]] {
			return fullRich[names[i]] > fullRich[names[j]]
		}
		return names[i] < names[j]
	})

	var b strings.Builder
	b.WriteString("# MCP schema weight (approx tokens, db.ApproxTokens)\n\n")
	b.WriteString("Generated by TestSchemaWeight_Report (`-update-schema-weight`). #2003.\n")
	b.WriteString("Weight = the tools/list entry a client receives (name + title +\ndescription + inputSchema + annotations), chars/4 heuristic.\n\n")
	b.WriteString("## Totals by mode\n\n")
	b.WriteString("| toolset | style | tools | total tokens |\n|---|---|--:|--:|\n")
	for _, c := range combos {
		nTools := len(fullRich)
		if c.toolset == "core" {
			nTools = len(coreToolset)
		}
		fmt.Fprintf(&b, "| %s | %s | %d | %d |\n", c.toolset, c.style, nTools, totals[c.toolset+"/"+c.style])
	}
	b.WriteString("\n## Per-tool weight, full/rich (heaviest first)\n\n")
	b.WriteString("| tool | tokens | core |\n|---|--:|:--:|\n")
	for _, name := range names {
		core := ""
		if coreToolset[name] {
			core = "x"
		}
		fmt.Fprintf(&b, "| %s | %d | %s |\n", name, fullRich[name], core)
	}

	got := []byte(b.String())
	goldenPath := filepath.Join("testdata", "schema-weight.md")
	if *updateSchemaWeight {
		if err := os.WriteFile(goldenPath, got, 0o644); err != nil {
			t.Fatalf("write %s: %v", goldenPath, err)
		}
		t.Logf("rewrote %s (full/rich total %d tokens)", goldenPath, totals["full/rich"])
		return
	}
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read %s: %v\n  Run `go test ./internal/server/ -run TestSchemaWeight_Report -update-schema-weight` to create it.", goldenPath, err)
	}
	if string(got) != string(want) {
		t.Errorf("schema weight diverged from %s — tool schemas changed size.\n"+
			"If intentional, regenerate with:\n"+
			"  go test ./internal/server/ -run TestSchemaWeight_Report -update-schema-weight\n"+
			"and review the diff (the diff IS the schema-cost change).", goldenPath)
	}
}

// TestSchemaWeight_CoreLean_UnderBudget is the permanent regression
// gate: the diet surface (core toolset + lean descriptions) must stay
// under coreLeanTokenBudget approximate tokens. If this fails, a
// schema/description grew — either shrink it or consciously raise the
// budget in review.
func TestSchemaWeight_CoreLean_UnderBudget(t *testing.T) {
	srv := newSchemaWeightServer(t, "core", "lean")
	perTool, total := schemaWeights(t, srv)
	if len(perTool) != len(coreToolset) {
		t.Errorf("core toolset advertises %d tools, want %d", len(perTool), len(coreToolset))
	}
	if total >= coreLeanTokenBudget {
		names := make([]string, 0, len(perTool))
		for n := range perTool {
			names = append(names, n)
		}
		sort.Slice(names, func(i, j int) bool { return perTool[names[i]] > perTool[names[j]] })
		var lines []string
		for _, n := range names {
			lines = append(lines, fmt.Sprintf("  %-14s %5d", n, perTool[n]))
		}
		t.Errorf("core+lean schema weight %d tokens >= budget %d.\nPer-tool (heaviest first):\n%s",
			total, coreLeanTokenBudget, strings.Join(lines, "\n"))
	}
	t.Logf("core+lean total: %d tokens (budget %d)", total, coreLeanTokenBudget)
}
